include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    import_of_legacy_library_into_null_safe: ignore
    avoid_print: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated_plugin_registrant.dart"