name: showcase_view
description: Showcase View module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.6.17+1
  url_launcher:
  flutter_modular:
  responsive_builder:
  common_ui:
    path: ../common_ui
  source_code_view:
    path: ../source_code_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.showcase_view
    iosBundleIdentifier: com.example.showcaseView
