name: three_cols_layout
description: Three Cols Layout module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add your dependency here
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fluwix.three_cols_layout
    iosBundleIdentifier: com.fluwix.threeColsLayout
