include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: false

analyzer:
#  errors:
#    import_of_legacy_library_into_null_safe: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - charts_gallery