name: adaptive_scaffold
description: Adaptive Scaffold module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_adaptive_scaffold: ^0.1.0
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/potato.png
    - assets/images/habanero.png
    - assets/images/strawberry.png
    - assets/images/plum.png
    - assets/images/mushroom.png
    - assets/images/avocado.png

  module:
    androidX: true
    androidPackage: com.fluwix.adaptive_scaffold
    iosBundleIdentifier: com.fluwix.adaptiveScaffold    
