name: ether_wallet
description: Ether Wallet module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  web3dart: ^2.3.3
  provider: ^6.0.2
  qr_flutter: ^4.0.0
  bip39: ^1.0.6
  hex: ^0.2.0
  shared_preferences: ^2.0.12
  web_socket_channel: ^2.1.0
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  qr_code_scanner: ^0.7.0
  url_launcher: ^6.0.18
  flutter_hooks: ^0.18.1
  built_value: ^8.1.4
  built_collection: ^5.1.1
  ed25519_hd_key: ^2.2.0
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints:
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4
  json_serializable: ^6.1.4  

flutter:
  uses-material-design: true
  
  assets:
    - TargaryenCoin.json

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
        
  module:
    androidX: true
    androidPackage: com.fluwix.ether_wallet
    iosBundleIdentifier: com.fluwix.etherWallet
