name: rich_text_editor
description: Rich Text Editor module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_quill: 9.0.1
  flutter_quill_extensions: 9.0.1
  flutter_quill_test: 9.0.1
  quill_html_converter:
    9.0.1

    # Normal Packages
  path: ^1.8.3
  equatable: ^2.0.5
  cross_file: ^0.3.3+6
  cached_network_image: ^3.3.0

  # Bloc libraries
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  # Freezed
  freezed_annotation: ^2.4.1

  # Json
  json_annotation: ^4.8.1

  # Plugins
  image_cropper: ^5.0.0
  path_provider: ^2.1.1
  # For drag and drop feature
  desktop_drop: ^0.4.4
  # For picking quill document files
  file_picker: ^6.1.1
  # For sharing text
  share_plus: ^7.2.1
  super_clipboard: ^0.7.3

  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: monospace
      fonts:
        - asset: assets/fonts/MonoSpace.ttf
    - family: serif
      fonts:
        - asset: assets/fonts/Serif.ttf
    - family: sans-serif
      fonts:
        - asset: assets/fonts/SansSerif.ttf
    - family: ibarra-real-nova
      fonts:
        - asset: assets/fonts/IbarraRealNova-Regular.ttf
    - family: square-peg
      fonts:
        - asset: assets/fonts/SquarePeg-Regular.ttf
    - family: nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: roboto-mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: SF-UI-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf

  module:
    androidX: true
    androidPackage: com.fluwix.rich_text_editor
    iosBundleIdentifier: com.fluwix.richTextEditor
