name: rich_text_editor
description: Rich Text Editor module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  path: ^1.9.1

  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_quill_test: ^11.1.0
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  module:
    androidX: true
    androidPackage: com.fluwix.rich_text_editor
    iosBundleIdentifier: com.fluwix.richTextEditor
