name: search_bar
description: Search Bar module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_floating_search_bar_2: ^0.5.0
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fluwix.search_bar
    iosBundleIdentifier: com.fluwix.searchBar
