// Mocks generated by Mockito 5.0.10 from annotations
// in number_trivia/test/domain/usecases/get_concrete_number_trivia_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:number_trivia/common/presentation/input_converter.dart' as _i5;
import 'package:number_trivia/domain/entities/number_trivia.dart' as _i2;
import 'package:number_trivia/domain/repositories/number_trivia_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeNumberTrivia extends _i1.Fake implements _i2.NumberTrivia {}

/// A class which mocks [NumberTriviaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumberTriviaRepository extends _i1.Mock
    implements _i3.NumberTriviaRepository {
  MockNumberTriviaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NumberTrivia> getConcreteNumberTrivia(int? number) =>
      (super.noSuchMethod(Invocation.method(#getConcreteNumberTrivia, [number]),
              returnValue: Future<_i2.NumberTrivia>.value(_FakeNumberTrivia()))
          as _i4.Future<_i2.NumberTrivia>);
  @override
  _i4.Future<_i2.NumberTrivia> getRandomNumberTrivia() =>
      (super.noSuchMethod(Invocation.method(#getRandomNumberTrivia, []),
              returnValue: Future<_i2.NumberTrivia>.value(_FakeNumberTrivia()))
          as _i4.Future<_i2.NumberTrivia>);
}

/// A class which mocks [InputConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputConverter extends _i1.Mock implements _i5.InputConverter {
  MockInputConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int stringToUnsignedInteger(String? string) =>
      (super.noSuchMethod(Invocation.method(#stringToUnsignedInteger, [string]),
          returnValue: 0) as int);
}
