name: surrealdb_console
description: Surrealdb Console module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  console:
    path: ../console
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view
  surrealdb_wasm: ^0.7.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fluwix.surrealdb_console
    iosBundleIdentifier: com.fluwix.surrealdbConsole
