name: number_trivia
description: Number Trivia module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^8.0.3
  # Clean Architecture
  flutter_clean_architecture: ^6.0.2
  # Remote API
  connectivity_plus: ^6.1.4
  # Local cache
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  # Code generator for unions/pattern-matching/copy/toJson/fromJson
  freezed_annotation:

  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view

dependency_overrides:
  pub_semver: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  pedantic:
  build_runner:
  freezed:
  json_serializable:
  file: ^6.1.4

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fluwix.number_trivia
    iosBundleIdentifier: com.fluwix.numberTrivia

scripts:
  generate: flutter pub run build_runner build
