name: wallet_connect_showcase
description: Wallet Connect Showcase module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 

  scan: ^1.4.3
  web3dart: ^2.6.1
  shared_preferences: ^2.0.7
  flutter_inappwebview: ^6.1.5
  cupertino_icons: ^1.0.2
  eth_sig_util: ^0.0.3
  wallet_connect: ^1.0.4
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fluwix.wallet_connect_showcase
    iosBundleIdentifier: com.fluwix.walletConnectShowcase
